server:
  port: 8888
spring:
  application:
    name: congig-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landarani/abnamro-config.git
          repos:
            local:
              pattern: local*
              uri: file://${user.home}/local-config
  jackson:
    serialization:
      indent_output: true